# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d1890078d90cec07cb2dbb6b5d321075af68591dbb57e2f81de6397131c5b440c3f49c7f764826cb1c6e246973782b43953fedbcbf4dcc9e15410f71afa6810

test:
  secret_key_base: ea91e6413510c048b73a6dd21fcedc4bc630a6a47eebdde8ffe2a674d88f0ba7be1f9d94b32a8e9cfc172642b5c3d990633ed065ed0449e9c0b577d0de91dc15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
